"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Bird_1 = require("./Bird");
var Mammal_1 = require("./Mammal");
var mam = new Mammal_1.Mammal("bear", 20, "white");
console.log("name: ".concat(mam.getName(), ", age: ").concat(mam.getAge(), ", coat: ").concat(mam.getCoat()));
mam.emitSound("uuugrhh");
mam.breastfood();
var bird = new Bird_1.Bird("macaw", 2, 10);
console.log("name: ".concat(bird.getName(), ", age: ").concat(bird.getAge(), ", wingspan ").concat(bird.getWingspan()));
bird.emitSound("piupiu");
bird.fly();
console.log("updated info:");
mam.setAge(14);
mam.setName("elephant");
mam.setCoat("gray");
console.log("name: ".concat(mam.getName(), ", age: ").concat(mam.getAge(), ", coat: ").concat(mam.getCoat()));
bird.setAge(4);
bird.setName("parrot");
bird.setWingspan(7);
console.log("name: ".concat(bird.getName(), ", age: ").concat(bird.getAge(), ", wingspan ").concat(bird.getWingspan()));
